#### 경로 찾기

In [53]:
import json
path = ''
lines = open(path, encoding='utf-8').readlines()
records = [json.loads(line) for line in lines]

FileNotFoundError: [Errno 2] No such file or directory: ''

In [68]:
from pandas import DataFrame, Series
import pandas as pd

## DataFrame
- row와 column으로 구성
- 여러 개의 Series, Series = array + Schema (col_name, dtype)
- arrays + Schemas

- row(행) : record, instance, observative, observation, tuple
- column(열) : 특성, 독립변수(x), column 마다 dtype이 다를 수 있다. 1개의 column은 array로 구성됨. = Series
- column은 같은 key값들을 가지고 있으며, dtype이 동일하다.

In [5]:
# df = DataFrame(L({k: v}))

#### DataFrame 객체를 만드는 방법

In [38]:
df = DataFrame(list({'k1': 'v1'})) # DF생성자 함수

In [39]:
df[0]

0    k1
Name: 0, dtype: object

In [40]:
d = {"a": 1, "b": 5, "c": 7}
df2 = DataFrame(list(d))

#### DataFrame key indexing and slicing

In [ ]:
df[['key1', 'key2']][:] # 여러 개의 Series를 불러올 때. 즉, dataframe 형태로 불러옴. dataframe 함수를 적용할 수 있음.

In [ ]:
df['key1'][:] # 1개의 Series만 호출. 즉, Series 형태로 불러온 것. dataframe에서 사용하는 함수 사용 불가능.

#### Series.빈도표의 생성
data frame인 frame의 하나의 필드는 Series 객체인데, 이 객체는 value_counts라는 메소드를 가지고 있어서 쉽게 빈도를 구할 수 있다.

>**Series.value_counts**(normalize=False, sort=True, ascending=False, bins=None, dropna=True)
- Returns object containing counts of unique values.

- nomalize : 정규화, 전체 중에서 차지하는 비율을 알아보기 위함. / 차지하는 비율 제공
- bins : 구간의 수를 설정하기 위함. 명목적 변수는 사용X, 연속적 값을 가지는 변수 일 때 사용  
지정 구간의 수 = (Max-min) / bins cf) width = 각 구간의 차이 
- dropna : 결측치를 None 값을 제거하기 위함. / 결측치 제거

```python
tz_counts = frame['tz'].value_counts()
tz_counts[:10]
```

- NA, None, Null (결측치 처리 시 생각할 것)

1. key X, value X : None
2. Key O, value X : Null
3. Key X, value O : NA , Pandas : NaN (Not application Number)

#### 필드가 결측된 값(Na;Nan)은 missing으로 대체하고 Null 값은 Unknown으로 대체한다.

```python
clean_tz = frame['tz'].fillna('Missing')
clean_tz[clean_tz == ''] = 'Unknown' # 기존 Series Indexing과 boolean 조건식, clean_tz == ''
tz_counts = clean_tz.value_counts()
tz_counts[:10]
```

#### boolean 조건식 설정 예시

```python
clean_tz[:5][[True, False, True, True, False]]
b = [True, False, True, True, False] # 색인을 담은 Vector
clean_tz[:5][b] # 색인
```

#### Series

In [7]:
import numpy as np

In [11]:
l = [4, 2, 3 ,1]
a = np.array([4, 2, 3 ,1])
obj = Series(a, copy=True)
obj

0    4
1    2
2    3
3    1
dtype: int32

In [ ]:
# copy

In [26]:
a[0] = 3
obj

0    4
1    2
2    3
3    1
dtype: int32

In [ ]:
# reference

In [28]:
obj[0] = 4
obj

0    4
1    2
2    3
3    1
dtype: int32

In [51]:
3 in obj

True

In [39]:
d = dict(obj)
print(obj)
d

0    4
1    2
2    3
3    1
dtype: int32


{0: 4, 1: 2, 2: 3, 3: 1}

In [42]:
d[['0','1']] = 6 # dict에서는 안 됨.
# fancy indexing과 boolean indexing은 numpy나 built-in array에서만 
# 이 방법들은 연속적인 값들이 데이터에 존재할 때, 사용할 수 있다. list, set, tuple, dict에서는 안 됨.

TypeError: unhashable type: 'list'

In [ ]:
# for k in dict:
# for k in array:

In [36]:
# Series의 index에 접근하는 방법

In [34]:
obj.index.values

array([0, 1, 2, 3], dtype=int64)

In [35]:
np.exp(obj)

0    54.598150
1     7.389056
2    20.085537
3     2.718282
dtype: float64

In [43]:
# Seies의 ndarray 연산

- Na 
- null
- isna == isnull
- notna == notnull

In [ ]:
# missing

In [54]:
obj.isna()

0    False
1    False
2    False
3    False
dtype: bool

In [55]:
obj.notna()

0    True
1    True
2    True
3    True
dtype: bool

In [60]:
obj.name = None
obj.index.name = '순번'
obj

순번
0    4
1    2
2    3
3    1
dtype: int32

In [62]:
type(obj.name)

NoneType

In [66]:
obj.index = ['a', 'b', 'c', 'd']
obj 

a    4
b    2
c    3
d    1
dtype: int32

In [121]:
# reindex 시에는 index가 서로 동일하지 않으면 다른 만큼 결측치가 생긴다.

In [ ]:
# 예시

- Series, Numpy array fancy indexing

- obj[3] O
- obj[3,4] X -> # fanct indexing으로 obj[[3, 4]] 이런식으로

#### DataFrame

- array-like로서 shape는 (n, p)로 구성된다.

- Columns = Column name들을 가지고 있는 array이다. 따라서 columns의 name도 따로 지정 가능.
- 동일한 key 유형을 갖는 Series 객체를 원소로하는 dict

In [75]:
frame = DataFrame(data=arr)

df -> {S1.name:S1, S2.name:S2, S3.name:S3} df은 dict로 columns를 가지고 있음.

In [71]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- numpy array와 Series에서는 fancy indexing으로 동작하지만,

In [72]:
arr[[0,3], [0, 2]] # 0,0 3,2

array([ 0, 14])

- dataframe에서는 cartesian production indexing이 발생함. 
- why? data type도 무너지고 형태도 망가지기때문에 데이터 형태 유지하기 위함.

In [76]:
frame.iloc[[0, 3], [0, 2]] 

0   2
0   0   2
3  12  14

- object = 최상위 객체 (int, stiring, boolean등 모든 형태를 다 통칭함.)

In [77]:
frame.columns

RangeIndex(start=0, stop=4, step=1)

In [78]:
frame.index

RangeIndex(start=0, stop=4, step=1)

In [79]:
frame.index.values

array([0, 1, 2, 3], dtype=int64)

In [83]:
frame.shape[0]

4

#### DataFrame의 column 접근법

```python
frame['col1'] # 1개의 column 호출하고, Series로 불러옴. 즉, 차원 축소

frame[['co1']] # 1개의 column 호출하지만 dataframe 형식

frame[['co1', 'col2']] # 2개의 column 호출하고 dataframe 형식
```

In [120]:
# 내용 추가
frame.ix
frame.iloc

C:\Users\tmznq\Anaconda3\envs\ml_scratch\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


- column에 대한 직접적인 치환(대입)이 가능하다.

```python
frame2['col2']
l = [1, 2, 3, 4, 5]
frame2['col2'] = l # col2가 가진 values와 같은 수의 values를 가지고 있어야 한다.
frame2
```

- Series로 대입하는 경우, row index에 의해 치환이 이루어지며 누락된 index에는 NaN

In [ ]:
# 내용 추가

In [ ]:
val = Series([1, 2, 3, 4])

- 현재 존재하지 않는 column을 대입하면, 새로 생성된다.

In [ ]:
# 내용 추가

In [ ]:
frame.col # col1 이라는 이름을 갖는 Series이다.

- DataFrame에 대한 변경을 원치 않는다면, copy()를 사용한다.
- del 명령어로 원하는 column 삭제 가능

In [ ]:
del frame['co1']

중첩된 dictionary를 이용하여 nested key를 row index로 사용할 수 있음.

In [101]:
dict2 = {'a': {2001: 2.4, 2002: 2.9},
       'b': {2001: 3.3, 2002: 1.1, 2003: 1.2}}
frame3 = DataFrame(dict2)
frame3

a    b
2001  2.4  3.3
2002  2.9  1.1
2003  NaN  1.2

```python
C = DataFrame(dict2, index=[2001, 2002, 2003])
# dict2는 이미 index를 담고 있으므로, index를 재지정할 때 오류가 발생한다.
```

- dict indexing할 때, error 피하는 법
```python
df = DataFrame(data)
df.columns = [columns]
```

- dict 속의 dict에서 key(column)와 row(index) 잘 찾아보자

#### cf) dict를 성분으로하는 list에서 DataFrame 생성하기.

In [119]:
dict4 =[{2001: 2.4, 2002: 2.9},
       {2001: 3.3, 2002: 1.1, 2003: 1.2}]
DataFrame(dict4)
# 그 전에 index로 인식했었지만 위와 같은 경우에는 column으로 인식된다는 사실.

2001  2002  2003
0   2.4   2.9   NaN
1   3.3   1.1   1.2

In [100]:
frame3.T

2001  2002  2003
a   2.4   2.9   NaN
b   3.3   1.1   1.2

#### transposing

In [114]:
dict3 = {'a': {2001: 2.4, 2002: 2.9},
        'b': {2001: 3.3, 2002: 1.1, 2003: 1.2},
        'c': {2001: 'abc', 2002: 'bcf', 2003: 'eee'}}
frame2 = DataFrame(dict3)
frame2

a    b    c
2001  2.4  3.3  abc
2002  2.9  1.1  bcf
2003  NaN  1.2  eee

In [116]:
frame2.T

2001 2002 2003
a  2.4  2.9  NaN
b  3.3  1.1  1.2
c  abc  bcf  eee

- Transposing을 하게되면 col의 dtype들이 전부 같지 않아도 강제로 형변환이 이루어 진다는 것을 알 수 있음.

#### naming

In [123]:
frame2

a    b    c
2001  2.4  3.3  abc
2002  2.9  1.1  bcf
2003  NaN  1.2  eee

In [124]:
frame2.index.name = 'year'; frame2.columns.name = 'alpha'
frame2

alpha    a    b    c
year                
2001   2.4  3.3  abc
2002   2.9  1.1  bcf
2003   NaN  1.2  eee

- 이름을 정해주는 것은 중복된 indexing을 하기 위해서 사용한다. ex) 은행의 연간 보고서 (분기별 매출액, 지점을 시와 구로 세분화 가능)

#### values

In [125]:
frame2.values

array([[2.4, 3.3, 'abc'],
       [2.9, 1.1, 'bcf'],
       [nan, 1.2, 'eee']], dtype=object)

In [126]:
frame2.columns

Index(['a', 'b', 'c'], dtype='object', name='alpha')

#### index object

pandas의 index 객체는 표 형식의 data에서 각 row와 columns에 대한 name과 metadata를 저장하는 객체이다.
- 색인 객체는 변경할 수 없다.(immutable)
- 변경 불가능한 특성 떄문에 자료 구조 사이에서 안전하게 공유된다.

In [128]:
frame2.columns[1]

'b'

```python
frame2.columns[1] = 'd' # 이를 실행하면 오류가 난다. why? immutable한 특성을 가지기 때문임.
```

In [ ]:
# index / append : index를 바꿀 수 없기때문에, 새로운 index를 추가하면서 완전히 새로운 index 객체를 만들어 낸다.

In [ ]:
# append / insert : append는 끝에 추가, insert는 중간에 추가하는 것.

In [ ]:
# monotonic : 단조성을 가지는가? -> 시계열 index인지 확인하는 방법

In [132]:
obj = Series(range(3), index = ['a', 'b', 'c'])
index = obj.index

In [133]:
index[1:]

Index(['b', 'c'], dtype='object')

In [137]:
# immutable한 특성의 예시
try:
    index[2] = 3
except Exception:
    print("index is immutable")

index is immutable


In [138]:
frame2

alpha    a    b    c
year                
2001   2.4  3.3  abc
2002   2.9  1.1  bcf
2003   NaN  1.2  eee

In [140]:
'a' in frame2

True

In [150]:
frame2.index[1] in frame2

False

___

In [261]:
frame.loc[[0,1,2], 0] # 원하는 index와 column에 따른 값 반환 1

KeyError: 'None of [[0, 1, 2]] are in the [index]'

In [243]:
frame.loc[[0], [1, 3]]  # 원하는 index와 column에 따른 값 반환 2

1   3
0  1 NaN

#### reindex

In [253]:
# 새로운 색인에 맞도록 데이터 속 index를 재배열 하는 것.
frame2

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [256]:
frame2.reindex([2, 3, 1]) # 기존 frame의 index는 그대로 이며 새로운 index에 대한 객체가 생성됨.

0    1    2
2  6.0  7.0  8.0
3  NaN  NaN  NaN
1  3.0  4.0  5.0

In [257]:
frame2 # frame의 index는 유지되는 모습.

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

- index와 value의 관계 쌍은 유지되고
- 새로운 index의 value는 Na가 된다.

In [190]:
frame2 = DataFrame(np.arange(9).reshape(3,3), index=range(3), columns=range(3))
frame2.loc[0]

0    0
1    1
2    2
Name: 0, dtype: int32

In [250]:
frame = frame2.reindex(['하', '나', '도'])
frame.loc['하']

0   NaN
1   NaN
2   NaN
Name: 하, dtype: float64

In [242]:
frame = frame2.reindex(index=[0, 1, 2], columns=[0, 1, 3])
# column의 기존 값을 변경 시킨 NaN이 존재하는 frame[3]의 dtype은 float64로 전부 변경된다.
frame

0  1   3
0  0  1 NaN
1  3  4 NaN
2  6  7 NaN

In [240]:
# 여러가지 reindex method 참조.

In [247]:
frame

0  1   3
0  0  1 NaN
1  3  4 NaN
2  6  7 NaN

#### drop

In [259]:
# inplace : 자기자신 유지할 건지 말건지 설정하기.
# frame.drop()
# frame.drop_duplicates() : 복사된 동일한 내용의 데이터가 많이 들어왔을때, keep을 이용해서 1개만 남기고 전부 삭제 가능.

In [271]:
df = DataFrame(np.arange(12).reshape(3,4), columns = list("abcd"))
df

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [279]:
df.iloc[0,1] = 5; df.iloc[2,2] = 2

In [298]:
df.drop_duplicates() # keep : 남겨두는 위치 / 2가지 열을 볼 때는 중복되지 않을 수 있으므로 조심할 것.

a  b  c   d
0  0  5  2   3
1  4  5  6   7
2  8  9  2  11

In [299]:
df.iloc[2,1] = 5

In [301]:
df.drop_duplicates(['b','c'], keep='last') # 2가지 열의 중복된 값 비교 후 삭제.

a  b  c   d
1  4  5  6   7
2  8  5  2  11

#### indexing, slicing, filtering

- labeling slicing을 사용할 수 있다. 하지만 이는 indexing slicing과 다르게 끝 값이 포함된다.

In [311]:
df['b'] # column 접근

0    5
1    5
2    5
Name: b, dtype: int32

In [323]:
df.loc[:,'b':'d'] # column slicing

b  c   d
0  5  2   3
1  5  6   7
2  5  2  11

In [312]:
df.iloc[0] # row 접근

a    0
b    5
c    2
d    3
Name: 0, dtype: int32

In [317]:
df.iloc[0:3] # row slicing # 만약 row index가 object라면 loc으로 할 것.

a  b  c   d
0  0  5  2   3
1  4  5  6   7
2  8  5  2  11

In [361]:
df.T[df.T[1] > 4]

0  1   2
b  5  5   5
c  2  6   2
d  3  7  11

In [324]:
df[df > 1]

a  b  c   d
0  NaN  5  2   3
1  4.0  5  6   7
2  8.0  5  2  11

In [325]:
df[df['c'] > 2]

a  b  c  d
1  4  5  6  7

In [343]:
df.T[df.T[1] > 6]

0  1   2
d  3  7  11

In [331]:
def row_slicing(df, index, n):
    return df.T[df.T[index].T < n]

In [ ]:
# 범위를 지정한 column을 골라내기.
data[data.columns[data.loc['col_name'] < 10]]

In [332]:
row_slicing(df, 1, 6)

0  1  2
a  0  4  8
b  5  5  5